# animals_colors.yml
animals:
  - antelope
  - armadillo
  - badger
  - barracuda
  - bat
  - bear
  - beaver
  - bison
  - bobcat
  - buffalo
  - butterfly
  - camel
  - caribou
  - cheetah
  - cobra
  - cougar
  - coyote
  - crab
  - crocodile
  - deer
  - dingo
  - dolphin
  - dragonfly
  - eagle
  - eel
  - elephant
  - falcon
  - ferret
  - flamingo
  - fox
  - gazelle
  - gecko
  - giraffe
  - gorilla
  - grasshopper
  - hawk
  - hedgehog
  - hippopotamus
  - hornet
  - hummingbird
  - hyena
  - iguana
  - jaguar
  - kangaroo
  - koala
  - leopard
  - lion
  - lizard
  - lynx
  - mantis
  - meerkat
  - mole
  - moose
  - octopus
  - orangutan
  - orca
  - otter
  - owl
  - panther
  - parrot
  - penguin
  - porcupine
  - python
  - rabbit
  - raccoon

colors:
  - amber
  - amethyst
  - apricot
  - aquamarine
  - azure
  - beige
  - black
  - blue
  - blush
  - bronze
  - brown
  - burgundy
  - canary
  - carmine
  - cerulean
  - champagne
  - charcoal
  - cherry
  - chestnut
  - cobalt
  - coral
  - crimson
  - cyan
  - emerald
  - fawn
  - fuchsia
  - garnet
  - gold
  - goldenrod
  - gray
  - green
  - honey
  - indigo
  - ivory
  - jade
  - khaki
  - lavender
  - lemon
  - lilac
  - lime
  - magenta
  - maroon
  - mauve
  - midnight
  - mint
  - moss
  - navy
  - ochre
  - olive
  - onyx
  - opal
  - orange
  - peach
  - periwinkle
  - pink
  - plum
  - puce
  - purple
  - red
  - rose
  - ruby
  - sapphire
  - scarlet
  - silver
  - teal
  - turquoise
  - violet
  - white
  - yellow
